server:
  port: 8089

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/nvwa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: xxxx